### PR TITLE
Fix IE wire rendering and some other issues

### LINKED ISSUE #5: Immersive Engineering wires don't render.
### Expected Behavior
The wires are visible.

### Actual Behavior
The Immersive Engineering wires are invisible, I have tested this in all 3 renderer settings (2.0, 3.3, 4.3) and they stay invisible.

### Reproduction Steps
Simply use the Immersive Engineering wires normally and you'll notice they are missing. 

- Java Version: Adopt OpenJDK jre-8.0.252.09
- CPU: Intel i5 3330
- GPU: Zotac GTX750ti

### PR DESCRIPTION
**Pull request by malte0811**
Closes #5. The quad color and block render type commits are relevant to the issue, the other commits deal with issues I've run into on ForgeCraft.

Long IE wires still have some weird-looking glitches with the compact vertex format, but that is unavoidable as far as I can tell (simple integer overflow due to the massive models).

### CODE REVIEW

**Comment by hanetzer** [comment]
Nice, I'll have a look at this shortly. I recently reinstalled my operating system (switched from gentoo
to arch because emerge times were cutting down on my time to do 'real work') so it may be a bit.

**Comment by Edulml** [comment]
Don't know if this is the appropriate place to comment this, but here: I'm trying to compile a version of the mod with these additions to test it myself, but I'm having issues. I have successfully downloaded all the files from 1.16x/dev-forge including the changes from this pull request but my issue comes when trying to compile it with Gradle. when running the gradlew build command I get this error:

Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
  > Could not find com.feed_the_beast.mods:ftb-chunks:1.1.1.35_mapped_snapshot_20200916-1.16.2.
     Searched in the following locations:

And two other files it could not locate neither in my computer, nor on the web. Can I get some assistance, or a compiled build to test?

**Comment by Sparktion** [comment]
So, should I use this pull instead of the main version?

**Comment by hanetzer** [comment]
Merged. Sorry for the delay, the world has gone mad if you haven't noticed.

**Pull request closed without merging**
